name: CI Pipeline MLOps  # Workflow name (visible in GitHub UI)

# Trigger on push or PR to 'main' branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use GitHub's latest Ubuntu runner

    steps:
      # Checkout the repository (required to access source code)
      - name: Check out code  
        uses: actions/checkout@v3

      # Install Python 3.11
      - name: Set up Python  
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"  # Exact Python version to use

      # Install dependencies from requirements.txt
      - name: Install dependencies  
        run: pip install -r requirements.txt

      # Run pytest normally
      - name: Rodar testes  automatizados
        run: pytest test_pipeline.py
        
      # Run pytest with coverage (fail if coverage < 80%)
      - name: Run tests with coverage  
        run: |
          pytest --cov=./ \
                --cov-report=xml \
                --cov-fail-under=60 \
                test_pipeline.py

      # (Optional) withUpload coverage to Codecov
      - name: Upload coverage to Codecov  
        if: success()  # Only run if previous steps succeed
        uses: codecov/codecov-action@v3
